# Generated by Django 4.2.4 on 2023-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_chainofcustody_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleIntake',
            fields=[
                ('Default_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True, null=True)),
                ('SampleId', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('SampleName', models.CharField(blank=True, max_length=128, null=True)),
                ('Matrix', models.CharField(blank=True, max_length=128, null=True)),
                ('BatchNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('SampleSize', models.CharField(blank=True, max_length=128, null=True)),
                ('BatchSize', models.CharField(blank=True, max_length=128, null=True)),
                ('DistributorName', models.CharField(blank=True, max_length=128, null=True)),
                ('DistributorLicence', models.CharField(blank=True, max_length=128, null=True)),
                ('CustodyNumber', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChainOfCustody',
        ),
        migrations.DeleteModel(
            name='SampleIntakeForm',
        ),
        migrations.DeleteModel(
            name='SampleRetainForm',
        ),
        migrations.DeleteModel(
            name='SampleTrackingForm',
        ),
    ]
