# Generated by Django 4.2.4 on 2023-08-22 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_sampleintake_delete_chainofcustody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleintake',
            name='CurrentDate',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 22, 37, 34, 962624)),
        ),
    ]
