# Generated by Django 4.2.4 on 2023-08-22 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_sampleintake_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleintake',
            name='CurrentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
